repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: debug-statements
      - id: double-quote-string-fixer
      - id: no-commit-to-branch
        args: [ '--branch', 'master' ]
  - repo: https://github.com/ambv/black
    rev: 22.1.0
    hooks:
      - id: black
        language_version: python3.8
        args:
          - "--line-length=135"
          - "--skip-string-normalization"
        additional_dependencies: [ 'click==8.0.4' ]
  - repo: https://github.com/pycqa/flake8
    rev: 3.9.2
    # Убрать бы отсюда W605, но слишком много неправильных regex и их страшно менять
    hooks:
      - id: flake8
        args:
          - "--max-line-length=135"
          - "--ignore=E101,E203,E402,E501,W191,W503,F811,W605,F841"
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [ "--profile", "black" ]
