"""add counter notify

Revision ID: 36063d53d301
Revises: f4b27e7052d3
Create Date: 2024-04-18 10:48:48.876605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36063d53d301'
down_revision: Union[str, None] = 'f4b27e7052d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_meeting', sa.Column('date_create', sa.DateTime(), comment='Время создания встречи (UTC)'))
    op.add_column('user_meeting', sa.Column('notify_count', sa.Integer(), server_default=sa.text('0'), nullable=True, comment='Количество отправленных напоминаний'))
    op.drop_column('user_meeting', 'is_notify_first')
    op.drop_column('user_meeting', 'is_notify_second')
    op.drop_column('user_meeting', 'is_notify_last')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_meeting', sa.Column('is_notify_last', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True, comment='Указывает на отправку последнего уведомления'))
    op.add_column('user_meeting', sa.Column('is_notify_second', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True, comment='Указывает на отправку второго уведомления'))
    op.add_column('user_meeting', sa.Column('is_notify_first', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True, comment='Указывает на отправку первого уведомления'))
    op.drop_column('user_meeting', 'notify_count')
    op.drop_column('user_meeting', 'date_create')
    # ### end Alembic commands ###
