"""remove_fin_indicators

Revision ID: 0b2be2492b67
Revises: fdcaaa49ed47
Create Date: 2024-08-27 11:30:27.480096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0b2be2492b67'
down_revision: Union[str, None] = 'fdcaaa49ed47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('financial_indicators')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_indicators',
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column('2022', sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column('2023', sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column('2024E', sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column('2025E', sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column('2026E', sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column('alias', sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column('company', sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column('2020', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column('2021', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column('2022E', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column('2023E', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
