"""create relation_commodity_metals

Revision ID: 0c80ddce4b81
Revises: 2e8cea167b16
Create Date: 2024-03-28 17:26:31.659520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from migrations.data.make_rel_commodity_metals import base_rel_commodity_metals

# revision identifiers, used by Alembic.
revision: str = '0c80ddce4b81'
down_revision: Union[str, None] = '2e8cea167b16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def add_commodities_metals_data(relation_commodity_metals) -> None:
    op.bulk_insert(relation_commodity_metals, base_rel_commodity_metals.relation_commodity_metals)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    relation_commodity_metals = op.create_table(
        'relation_commodity_metals',
        sa.Column('commodity_id', sa.Integer(), nullable=False),
        sa.Column('name_from_source', sa.String(length=100), nullable=False),
        sa.Column('unit', sa.String(length=10), nullable=True),
        sa.Column('sub_name', sa.String(length=100), nullable=False),
        sa.ForeignKeyConstraint(['commodity_id'], ['commodity.id'],
                                onupdate='CASCADE', ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('commodity_id', 'name_from_source')
    )
    # ### end Alembic commands ###
    add_commodities_metals_data(relation_commodity_metals)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relation_commodity_metals')
    # ### end Alembic commands ###
