"""fin_summary unique constraint

Revision ID: 473e815e1353
Revises: 3fa6db967f0c
Create Date: 2024-06-17 10:54:19.916010

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '473e815e1353'
down_revision: Union[str, None] = '3fa6db967f0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade DB"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_primary_key('financial_summary_pkey', 'financial_summary', ['id'])
    op.execute(sa.sql.ddl.CreateSequence(sa.Sequence('financial_summary_id_seq')))
    op.alter_column('financial_summary', 'id',
                    existing_type=sa.BIGINT(),
                    server_default=sa.text("nextval('financial_summary_id_seq'::regclass)"),
                    existing_nullable=True)
    op.alter_column('financial_summary', 'sector_id',
                    existing_type=sa.TEXT(),
                    nullable=False,
                    comment='ID сектора на cib research')
    op.alter_column('financial_summary', 'company_id',
                    existing_type=sa.TEXT(),
                    nullable=False,
                    comment='ID клиента на cib research')
    op.alter_column('financial_summary', 'client_id',
                    existing_type=sa.BIGINT(),
                    type_=sa.Integer(),
                    nullable=False,
                    comment='ID клиента у нас в БД')
    op.alter_column('financial_summary', 'review_table',
                    existing_type=sa.TEXT(),
                    comment='Таблица с обзорной таблицей в формате dict',
                    existing_nullable=True)
    op.alter_column('financial_summary', 'pl_table',
                    existing_type=sa.TEXT(),
                    comment='Таблица с P&L таблицей в формате dict',
                    existing_nullable=True)
    op.alter_column('financial_summary', 'balance_table',
                    existing_type=sa.TEXT(),
                    comment='Таблица с балансной таблицей в формате dict',
                    existing_nullable=True)
    op.alter_column('financial_summary', 'money_table',
                    existing_type=sa.TEXT(),
                    comment='Таблица с таблицей денежных потоков в формате dict',
                    existing_nullable=True)
    op.create_unique_constraint('fin_indicator', 'financial_summary', ['sector_id', 'company_id', 'client_id'])
    op.create_foreign_key('financial_summary_client_id_fkey', 'financial_summary', 'client', ['client_id'], ['id'],
                          onupdate='CASCADE', ondelete='CASCADE')
    op.create_table_comment(
        'financial_summary',
        'Справочник таблиц с финансовыми показателями клиентов из CIB Research',
        existing_comment=None,
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade DB"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table_comment(
        'financial_summary',
        existing_comment='Справочник таблиц с финансовыми показателями клиентов из CIB Research',
        schema=None
    )
    op.drop_constraint('financial_summary_client_id_fkey', 'financial_summary', type_='foreignkey')
    op.drop_constraint('fin_indicator', 'financial_summary', type_='unique')
    op.drop_constraint('financial_summary_pkey', 'financial_summary', type_='primary')
    op.alter_column('financial_summary', 'money_table',
                    existing_type=sa.TEXT(),
                    comment=None,
                    existing_comment='Таблица с таблицей денежных потоков в формате dict',
                    existing_nullable=True)
    op.alter_column('financial_summary', 'balance_table',
                    existing_type=sa.TEXT(),
                    comment=None,
                    existing_comment='Таблица с балансной таблицей в формате dict',
                    existing_nullable=True)
    op.alter_column('financial_summary', 'pl_table',
                    existing_type=sa.TEXT(),
                    comment=None,
                    existing_comment='Таблица с P&L таблицей в формате dict',
                    existing_nullable=True)
    op.alter_column('financial_summary', 'review_table',
                    existing_type=sa.TEXT(),
                    comment=None,
                    existing_comment='Таблица с обзорной таблицей в формате dict',
                    existing_nullable=True)
    op.alter_column('financial_summary', 'client_id',
                    existing_type=sa.Integer(),
                    type_=sa.BIGINT(),
                    nullable=True,
                    comment=None,
                    existing_comment='ID клиента у нас в БД')
    op.alter_column('financial_summary', 'company_id',
                    existing_type=sa.TEXT(),
                    nullable=True,
                    comment=None,
                    existing_comment='ID клиента на cib research')
    op.alter_column('financial_summary', 'sector_id',
                    existing_type=sa.TEXT(),
                    nullable=True,
                    comment=None,
                    existing_comment='ID сектора на cib research')
    op.alter_column('financial_summary', 'id',
                    existing_type=sa.BIGINT(),
                    server_default=None,
                    existing_nullable=True,
                    autoincrement=True)
    op.execute(sa.sql.ddl.DropSequence(sa.Sequence('financial_summary_id_seq')))
    # ### end Alembic commands ###
