"""New column for tg groups

Revision ID: 259565411b58
Revises: bba2d88afbeb
Create Date: 2024-05-30 17:19:09.334418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from db import models
from migrations.data.new_column_for_tg_groups import general_name


# revision identifiers, used by Alembic.
revision: str = '259565411b58'
down_revision: Union[str, None] = 'bba2d88afbeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade_add_data(session: sa.orm.Session):
    for group_name, group_general_name in general_name.data.items():
        session.execute(
            sa.update(models.TelegramGroup).
            where(models.TelegramGroup.name == group_name).
            values(general_name=group_general_name)
        )
    session.commit()


def upgrade() -> None:
    conn = op.get_bind()
    session = sa.orm.Session(bind=conn)
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bot_telegram_group',
                  sa.Column('general_name', sa.String(length=255), nullable=False, server_default='',
                            comment='Наименование группы для меню новостей'))
    # ### end Alembic commands ###
    upgrade_add_data(session)


def downgrade() -> None:
    op.drop_column('bot_telegram_group', 'general_name')
