"""create user_dialog_history

Revision ID: 459389b1e781
Revises: 904899c37696
Create Date: 2024-05-17 13:05:13.972254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '459389b1e781'
down_revision: Union[str, None] = '904899c37696'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_dialog_history',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('knowledge_dialog', postgresql.JSONB(astext_type=sa.Text()), nullable=False,
              comment='Сообщения между Базой Знаний и пользователем'),
    sa.Column('giga_dialog', postgresql.JSONB(astext_type=sa.Text()), nullable=False,
              comment='Сообщения между Базой Знаний и пользователем'),
    sa.ForeignKeyConstraint(['user_id'], ['whitelist.user_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id'),
                            comment='Истории диалогов между пользователями и ИИ'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_dialog_history')
    # ### end Alembic commands ###
