"""add col to parser_source

Revision ID: 94be44f54cf9
Revises: 784715f9100c
Create Date: 2024-10-30 13:39:50.665288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from db.models import SourceGroup, ParserSource

# revision identifiers, used by Alembic.
revision: str = '94be44f54cf9'
down_revision: Union[str, None] = '784715f9100c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def add_to_source_group(session: sa.orm.Session, name: str, name_latin: str, last_id_: int) -> int:
    id_ = last_id_ + 1
    session.execute(sa.insert(SourceGroup).values(id=id_, name=name, name_latin=name_latin))
    session.commit()
    return id_


def add_to_parser_source(session: sa.orm.Session, name: str, source_group_id: int, last_id_: int) -> int:
    id_ = last_id_ + 1
    session.execute(sa.insert(ParserSource).values(
        id=id_,
        name=name,
        alt_names={},
        source='http://gigaparsers.ru:7000/get_articles/all',
        source_group_id=source_group_id,
    ))
    session.commit()
    return id_


def del_from_source_group(session: sa.orm.Session, name: str) -> None:
    query = sa.delete(SourceGroup).where(SourceGroup.name == name)
    session.execute(query)
    session.commit()


def upgrade() -> None:
    conn = op.get_bind()
    session = sa.orm.Session(bind=conn)
    last_id = session.execute(sa.select(SourceGroup.id).order_by(SourceGroup.id.desc())).scalar()
    tg_id_ = add_to_source_group(session, 'Отраслевые новости (тг)', 'tg_articles', last_id)
    sub_id_ = add_to_source_group(session, 'Новости по сущностям', 'subject_articles', tg_id_)

    last_id = session.execute(sa.select(ParserSource.id).order_by(ParserSource.id.desc())).scalar()
    tg_id_ = add_to_parser_source(session, 'Отраслевые новости (тг)', tg_id_, last_id)
    add_to_parser_source(session, 'Новости по сущностям', sub_id_, tg_id_)
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parser_source', sa.Column('last_save_datetime', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    conn = op.get_bind()
    session = sa.orm.Session(bind=conn)
    del_from_source_group(session, 'Отраслевые новости (тг)')
    del_from_source_group(session, 'Новости по сущностям')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parser_source', 'last_save_datetime')
    # ### end Alembic commands ###
