"""add fin company ps

Revision ID: 8faf87b5512c
Revises: 8573660fb1c0
Create Date: 2024-06-27 11:53:11.703418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from db.models import Client, FinancialSummary, ParserSource

# revision identifiers, used by Alembic.
revision: str = '8faf87b5512c'
down_revision: Union[str, None] = '8573660fb1c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


URL = 'https://research.sberbank-cib.com/group/guest/companies?companyId='


def upgrade_add_ps_for_financial_summary(session: sa.orm.Session):
    stmt = (
        sa.select(Client.name, FinancialSummary.company_id).
        select_from(FinancialSummary).
        join(Client, Client.id == FinancialSummary.client_id)
    )
    clients_ids = session.execute(stmt).all()
    for client_id_tuple in clients_ids:
        query = sa.insert(ParserSource).values(
            name=f'Финансовые показатели: {client_id_tuple[0]}',
            source_group_id=7,
            source=f'{URL}{client_id_tuple[1]}',
            alt_names={},
        )
        session.execute(query)


def downgrade_add_ps_for_financial_summary(session: sa.orm.Session):
    session.execute(sa.delete(ParserSource).where(ParserSource.source.like(URL + '%')))


def upgrade() -> None:
    conn = op.get_bind()
    session = sa.orm.Session(bind=conn)
    upgrade_add_ps_for_financial_summary(session)
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    conn = op.get_bind()
    session = sa.orm.Session(bind=conn)
    downgrade_add_ps_for_financial_summary(session)
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
