"""cib_research_tables_update_for_analytical_menu

Revision ID: fb7cacc642f5
Revises: 994960708c4c
Create Date: 2024-04-08 17:09:33.258391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import Session

from constants import enums
from db.models import ResearchGroup, ResearchSection, ResearchType


# revision identifiers, used by Alembic.
revision: str = 'fb7cacc642f5'
down_revision: Union[str, None] = '994960708c4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade_update_section_type_in_research_section(session: Session) -> None:
    stmt = (
        sa.update(ResearchSection).
        where(ResearchSection.name == 'Экономика').
        values(section_type=enums.ResearchSectionType.economy.value)
    )
    session.execute(stmt)
    stmt = (
        sa.update(ResearchSection).
        where(ResearchSection.name == 'Валютный рынок и процентные ставки').
        values(section_type=enums.ResearchSectionType.financial_exchange.value)
    )
    session.execute(stmt)


def upgrade_update_summary_type_in_research_type(session: Session) -> None:
    subquery = sa.select(ResearchSection.id).where(ResearchSection.name == 'Валютный рынок и процентные ставки')

    stmt = (
        sa.update(ResearchType).
        where(
            ResearchType.name != 'Ежедневные обзоры',
            ResearchType.research_section_id.in_(subquery),
        ).
        values(summary_type=enums.ResearchSummaryType.last_actual.value)
    )
    session.execute(stmt)

    subquery = sa.select(ResearchGroup.id).where(ResearchGroup.name == 'Клиенты')
    subquery = sa.select(ResearchSection.id).where(ResearchSection.research_group_id.in_(subquery))
    stmt = (
        sa.update(ResearchType).
        where(ResearchType.research_section_id.in_(subquery)).
        values(summary_type=enums.ResearchSummaryType.analytical_indicators.value)
    )
    session.execute(stmt)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('research_section',
                  sa.Column(
                      'section_type',
                      sa.Integer(),
                      server_default=str(enums.ResearchSectionType.default.value),
                      nullable=True,
                      comment='тип раздела из enums.ResearchSectionType (зависит формирование меню аналитики)',
                  ))
    op.add_column('research_type',
                  sa.Column(
                      'summary_type',
                      sa.Integer(),
                      server_default=str(enums.ResearchSummaryType.periodic.value),
                      nullable=True,
                      comment=(
                          'тип формирования сводки отчетов CIB Research '
                          'из enums.ResearchSummaryType (зависит формирование меню аналитики)'
                      ),
                  ))
    # ### end Alembic commands ###
    bind = op.get_bind()
    session = Session(bind=bind)

    upgrade_update_section_type_in_research_section(session)
    upgrade_update_summary_type_in_research_type(session)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('research_type', 'summary_type')
    op.drop_column('research_section', 'section_type')
    # ### end Alembic commands ###
