"""empty message

Revision ID: 3fa6db967f0c
Revises: f4b27e7052d3
Create Date: 2024-04-19 13:06:29.483279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import delete
from sqlalchemy.orm import Session

from db import models
from migrations.data import financial_summary

# revision identifiers, used by Alembic.
revision: str = '3fa6db967f0c'
down_revision: Union[str, None] = 'f4b27e7052d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def delete_new_sources(session: Session) -> None:
    delete_ids = [i['id'] for i in financial_summary.financial_summary]
    stmt = delete(models.financial_summary).where(models.financial_summary.id.in_(delete_ids))
    session.execute(stmt)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    financial_summary_table = op.create_table('financial_summary',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), nullable=False),
    sa.Column('sector_id', sa.Text(), nullable=False, comment='ID сектора на cib research'),
    sa.Column('company_id', sa.Text(), nullable=False, comment='ID клиента на cib research'),
    sa.Column('client_id', sa.Integer(), nullable=False, comment='ID клиента у нас в БД'),
    sa.Column('review_table', sa.Text(), nullable=True, comment='Таблица с обзорной таблицей в формате dict'),
    sa.Column('pl_table', sa.Text(), nullable=True, comment='Таблица с P&L таблицей в формате dict'),
    sa.Column('balance_table', sa.Text(), nullable=True, comment='Таблица с балансной таблицей в формате dict'),
    sa.Column('money_table', sa.Text(), nullable=True, comment='Таблица с таблицей денежных потоков в формате dict'),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Справочник таблиц с финансовыми показателями клиентов из CIB Research'
    )
    # ### end Alembic commands ###
    op.bulk_insert(financial_summary_table, financial_summary.financial_summary)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('financial_summary')
    # ### end Alembic commands ###
