"""create_rcm_update_ps

Revision ID: 994960708c4c
Revises: da0b40a4facd
Create Date: 2024-04-01 09:21:15.210953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from db.models import ParserSource, SourceGroup
from migrations.data.create_rel_commodity_metals import base_rel_commodity_metals


# revision identifiers, used by Alembic.
revision: str = '994960708c4c'
down_revision: Union[str, None] = '2e8cea167b16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade_update_row_in_parser_source(session: sa.orm.Session) -> None:
    stmt = (
        sa.update(ParserSource).
        where(ParserSource.source == 'https://tradingeconomics.com/commodities').
        values(name='Tradingeconomics Commodities', response_format=None)
    )
    session.execute(stmt)


def downgrade_update_row_in_parser_source(session: sa.orm.Session) -> None:
    stmt = (
        sa.update(ParserSource).
        where(ParserSource.source == 'https://tradingeconomics.com/commodities').
        values(name='Алюминий', response_format='Алюминий')
    )
    session.execute(stmt)


def upgrade_insert_row_in_parser_source(session: sa.orm.Session) -> None:
    stmt = sa.insert(ParserSource).values(
        name='LNG Japan/Korea',
        alt_names=[],
        source='https://www.investing.com/commodities/lng-japan-korea-marker-platts-futures',
        source_group_id=sa.select(SourceGroup.id).where(SourceGroup.name_latin == 'metals')
    )
    session.execute(stmt)


def downgrade_insert_row_in_parser_source(session: sa.orm.Session) -> None:
    stmt = sa.delete(ParserSource).where(
        source='https://www.investing.com/commodities/lng-japan-korea-marker-platts-futures'
    )
    session.execute(stmt)


def add_commodities_metals_data(relation_commodity_metals) -> None:
    op.bulk_insert(relation_commodity_metals, base_rel_commodity_metals.relation_commodity_metals)


def upgrade() -> None:
    bind = op.get_bind()
    session = sa.orm.Session(bind=bind)
    upgrade_update_row_in_parser_source(session)
    upgrade_insert_row_in_parser_source(session)
    session.commit()
    # ### commands auto generated by Alembic - please adjust! ###
    relation_commodity_metals = op.create_table(
        'relation_commodity_metals',
        sa.Column('commodity_id', sa.Integer(), nullable=False),
        sa.Column('name_from_source', sa.String(length=100), nullable=False),
        sa.Column('unit', sa.String(length=10), nullable=True),
        sa.Column('sub_name', sa.String(length=100), nullable=False),
        sa.ForeignKeyConstraint(['commodity_id'], ['commodity.id'],
                                onupdate='CASCADE', ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('commodity_id', 'name_from_source')
    )
    # ### end Alembic commands ###
    add_commodities_metals_data(relation_commodity_metals)


def downgrade() -> None:
    bind = op.get_bind()
    session = sa.orm.Session(bind=bind)
    downgrade_update_row_in_parser_source(session)
    downgrade_insert_row_in_parser_source(session)
    session.commit()
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relation_commodity_metals')
    # ### end Alembic commands ###
