"""add parent_report_id to research

Revision ID: b200c7468152
Revises: 3121e35c7891
Create Date: 2024-09-24 17:12:28.091390

"""
import json
from typing import Sequence, Union
from pathlib import Path

from alembic import op
import sqlalchemy as sa

from db.models import Research

# revision identifiers, used by Alembic.
revision: str = 'b200c7468152'
down_revision: Union[str, None] = '3121e35c7891'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

IDS_PATH = Path('migrations/data/add_parent_report_id/child_parent_reports_ids.json')


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('research_report_id_key', 'research', ['report_id'])
    op.add_column('research', sa.Column('parent_report_id', sa.String(length=64),
                                        nullable=True, unique=False))
    op.create_foreign_key(None, 'research', 'research',
                          ['parent_report_id'], ['report_id'],
                          onupdate='CASCADE', ondelete='RESTRICT')
    # ### end Alembic commands ###
    conn = op.get_bind()
    session = sa.orm.Session(bind=conn)
    reports_ids: dict[str, str] = json.loads(IDS_PATH.read_text())
    for child_id, parent_id in reports_ids.items():
        session.execute(
            sa.update(Research)
            .where(Research.report_id == child_id)
            .values(parent_report_id=parent_id)
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('research', 'parent_report_id')
    op.drop_constraint('research_report_id_key', 'research', type_='unique')
    # ### end Alembic commands ###
