"""create_relation_commodity

Revision ID: da0b40a4facd
Revises: 4effee5d98ff
Create Date: 2024-03-29 16:20:11.913828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from migrations.data.create_rel_commodity_metals import base_rel_commodity_metals


# revision identifiers, used by Alembic.
revision: str = 'da0b40a4facd'
down_revision: Union[str, None] = '4effee5d98ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def add_commodities_metals_data(relation_commodity_metals) -> None:
    op.bulk_insert(relation_commodity_metals, base_rel_commodity_metals.relation_commodity_metals)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    relation_commodity_metals = op.create_table(
        'relation_commodity_metals',
        sa.Column('commodity_id', sa.Integer(), nullable=False),
        sa.Column('name_from_source', sa.String(length=100), nullable=False),
        sa.Column('unit', sa.String(length=10), nullable=True),
        sa.Column('sub_name', sa.String(length=100), nullable=False),
        sa.ForeignKeyConstraint(['commodity_id'], ['commodity.id'],
                                onupdate='CASCADE', ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('commodity_id', 'name_from_source')
    )
    # ### end Alembic commands ###
    add_commodities_metals_data(relation_commodity_metals)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relation_commodity_metals')
    # ### end Alembic commands ###
