"""create user dialog and update feedback

Revision ID: 3fa97c15a5b2
Revises: bba2d88afbeb
Create Date: 2024-05-23 11:05:13.612481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3fa97c15a5b2'
down_revision: Union[str, None] = 'bba2d88afbeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_dialog_history',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('dialog', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Сообщения между ИИ и пользователем'),
    sa.ForeignKeyConstraint(['user_id'], ['whitelist.user_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id'),
    comment='Истории диалогов между пользователями и ИИ'
    )
    op.add_column('rag_user_feedback', sa.Column('history_rephrase_query', sa.Text(), nullable=True))
    op.add_column('rag_user_feedback', sa.Column('rephrase_query', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rag_user_feedback', 'rephrase_query')
    op.drop_column('rag_user_feedback', 'history_rephrase_query')
    op.drop_table('user_dialog_history')
    # ### end Alembic commands ###
