"""industry_analytics

Revision ID: 05f489c8c9ce
Revises: cb0c129f1d44
Create Date: 2024-04-24 13:28:15.236773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05f489c8c9ce'
down_revision: Union[str, None] = 'cb0c129f1d44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_industry_documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='id файла в базе'),
    sa.Column('file_name', sa.String(length=255), nullable=False, comment='Имя файла'),
    sa.Column('file_path', sa.Text(), nullable=False, comment='Путь к файлу в системе'),
    sa.Column('description', sa.Text(), server_default=sa.text("''::text"), nullable=True, comment='Описание'),
    sa.Column('industry_id', sa.Integer(), nullable=True, comment='id отрасли'),
    sa.Column('industry_type', sa.Integer(), server_default='1', nullable=True, comment='тип отрасли'),
    sa.ForeignKeyConstraint(['industry_id'], ['industry.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Справочник файлов отраслевой аналитики'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bot_industry_documents')
    # ### end Alembic commands ###
