"""products_data

Revision ID: f68463ef31e6
Revises: 05f489c8c9ce
Create Date: 2024-04-25 17:18:31.684785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from migrations.data.products_data import new_models as models
from migrations.data.products_data import bot_product, bot_product_document, bot_product_group


# revision identifiers, used by Alembic.
revision: str = 'f68463ef31e6'
down_revision: Union[str, None] = '05f489c8c9ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade_insert_bot_product_group_data(session: sa.orm.Session) -> None:
    session.execute(
        sa.insert(models.ProductGroup),
        bot_product_group.data,
    )


def upgrade_insert_bot_product_data(session: sa.orm.Session) -> None:
    session.execute(
        sa.insert(models.Product).values(bot_product.data),
    )


def upgrade_insert_bot_product_document_data(session: sa.orm.Session) -> None:
    session.execute(
        sa.insert(models.ProductDocument).values(bot_product_document.data),
    )


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_product_group',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='id файла в базе'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Имя группы'),
    sa.Column('name_latin', sa.String(length=255), nullable=False, comment='Имя группы eng'),
    sa.Column('description', sa.Text(), server_default=sa.text("''::text"), nullable=True,
              comment='Описание группы (текст меню тг)'),
    sa.Column('display_order', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='Порядок отображения'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='group_name'),
    comment='Справочник групп продуктов (продуктовая полка, hot offers)'
    )
    op.create_table('bot_product',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='id файла в базе'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Имя продукта (кредит, GM, ...)'),
    sa.Column('description', sa.Text(), server_default=sa.text("''::text"), nullable=True,
              comment='Текст сообщения, которое выдается при нажатии на продукт'),
    sa.Column('display_order', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='Порядок отображения'),
    sa.Column('group_id', sa.Integer(), nullable=False, comment='id группы продукта'),
    sa.ForeignKeyConstraint(['group_id'], ['bot_product_group.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'group_id', name='product_name_in_group'),
    comment='Справочник категорий продуктов (кредит, GM, ...)'
    )
    op.create_table('bot_product_document',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='id файла в базе'),
    sa.Column('file_path', sa.Text(), nullable=False, comment='Путь к файлу в системе'),
    sa.Column('name', sa.String(length=255), nullable=False,
              comment='Наименование документа или продуктового предложения'),
    sa.Column('description', sa.Text(), server_default=sa.text("''::text"), nullable=True, comment='Описание'),
    sa.Column('product_id', sa.Integer(), nullable=False, comment='id категории продукта'),
    sa.ForeignKeyConstraint(['product_id'], ['bot_product.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Справочник файлов продуктов'
    )
    # ### end Alembic commands ###
    bind = op.get_bind()
    session = sa.orm.Session(bind=bind)

    upgrade_insert_bot_product_group_data(session)
    upgrade_insert_bot_product_data(session)
    upgrade_insert_bot_product_document_data(session)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bot_product_document')
    op.drop_table('bot_product')
    op.drop_table('bot_product_group')
    # ### end Alembic commands ###
