"""create links_queue

Revision ID: b6ec26f13742
Revises: 784715f9100c
Create Date: 2024-10-25 12:14:25.677926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'b6ec26f13742'
down_revision: Union[str, None] = '784715f9100c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('article_link_key', 'article', ['link'])
    op.create_table('article_online_pending_links_queue',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column(
            'type_of_link',
            sa.Enum('subject_link', 'tg_link', name='linkstype'), nullable=False, comment='Тип ссылки'
        ),
        sa.Column('link', sa.Text(), nullable=False, comment='Ссылка на новость'),
        sa.ForeignKeyConstraint(['link'], ['article.link'], onupdate='CASCADE', ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('link'),
        comment='Таблица, содержащая недавно сохраненные ссылки, для их обработки QABanker'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article_online_pending_links_queue')
    op.drop_constraint('article_link_key', 'article', type_='unique')
    sa.Enum('subject_link', 'tg_link', name='linkstype').drop(op.get_bind())
    # ### end Alembic commands ###
