name: CI_service
description: description description

on:
  workflow_call:
    inputs:
      service_path:
        description: Service directory
#        required: true
        type: string
      with_flake:
        description: Run flake8
        type: boolean

#        required: true
#        default: false

#      with_pylint:
#        description: Run pylint
#        type: boolean
#        required: false
#        default: false
#      with_tests:
#        description: Run tests
#        type: boolean
#        required: false
#        default: false

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          cache: poetry

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: TEST
        run: |
          env

#      - name: Run flake8
#        if: ${{ inputs.with_flake }}
#        run: |
#          poetry run python -m flake8 ${{ inputs.service_path }}
#
#      - name: Run pylint
#        if: ${{ inputs.with_flake }}
#        run: |
#          poetry run python -m pylint ${{ inputs.service_path }}
#
#      - name: Run pytest
#        if: ${{ inputs.with_flake }}
#        run: |
#          poetry run python -m pytest ${{ inputs.service_path }}