"""add names for rag

Revision ID: bba2d88afbeb
Revises: 904899c37696
Create Date: 2024-05-16 17:20:27.995582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from models import models
from migrations.data.add_names_for_rag.names import rag_names

# revision identifiers, used by Alembic.
revision: str = 'bba2d88afbeb'
down_revision: Union[str, None] = '904899c37696'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade_add_data(session: sa.orm.Session):
    for section_name, rag_name in rag_names.items():
        session.execute(
            sa.update(models.TelegramSection).
            where(models.TelegramSection.name == section_name).
            values(rag_name=rag_name)
        )
    session.commit()


def upgrade() -> None:
    conn = op.get_bind()
    session = sa.orm.Session(bind=conn)
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bot_telegram_section',
                  sa.Column('rag_name', sa.String(length=100), nullable=False, server_default='',
                            comment='Название секции для создания документов в RAG-сервисе'))
    # ### end Alembic commands ###
    upgrade_add_data(session)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bot_telegram_section', 'rag_name')
    # ### end Alembic commands ###
