"""fin_summary unique constraint

Revision ID: 473e815e1353
Revises: 3fa6db967f0c
Create Date: 2024-06-17 10:54:19.916010

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

from migrations.data import financial_summary


# revision identifiers, used by Alembic.
revision: str = '473e815e1353'
down_revision: Union[str, None] = '3fa6db967f0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade DB"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('financial_summary')

    financial_summary_table = op.create_table('financial_summary',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647,
                                                 cycle=False, cache=1), nullable=False),
    sa.Column('sector_id', sa.Text(), nullable=False, comment='ID сектора на cib research'),
    sa.Column('company_id', sa.Text(), nullable=False, comment='ID клиента на cib research'),
    sa.Column('client_id', sa.Integer(), nullable=False, comment='ID клиента у нас в БД'),
    sa.Column('review_table', sa.Text(), nullable=True, comment='Таблица с обзорной таблицей в формате dict'),
    sa.Column('pl_table', sa.Text(), nullable=True, comment='Таблица с P&L таблицей в формате dict'),
    sa.Column('balance_table', sa.Text(), nullable=True, comment='Таблица с балансной таблицей в формате dict'),
    sa.Column('money_table', sa.Text(), nullable=True, comment='Таблица с таблицей денежных потоков в формате dict'),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sector_id', 'company_id', 'client_id', name='fin_indicator'),
    comment='Справочник таблиц с финансовыми показателями клиентов из CIB Research')
    # ### end Alembic commands ###
    op.bulk_insert(financial_summary_table, financial_summary.financial_summary)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade DB"""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
