"""add cols to rag_user_feedback

Revision ID: 378aac2e1b79
Revises: bba2d88afbeb
Create Date: 2024-05-27 09:01:40.775904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '378aac2e1b79'
down_revision: Union[str, None] = 'bba2d88afbeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rag_user_feedback', sa.Column('history_query', sa.Text(), nullable=True, comment='Перефразированный на истории диалога запрос пользователя'))
    op.add_column('rag_user_feedback', sa.Column('history_response', sa.Text(), nullable=True, comment='Ответ на перефразированный на истории диалога запрос пользователя'))
    op.add_column('rag_user_feedback', sa.Column('rephrase_query', sa.Text(), nullable=True, comment='Перефразированный запрос пользователя'))
    op.add_column('rag_user_feedback', sa.Column('rephrase_response', sa.Text(), nullable=True, comment='Ответ на перефразированный запрос пользователя'))
    op.alter_column('rag_user_feedback', 'chat_id',
               existing_type=sa.BIGINT(),
               comment='ID чата с пользователем',
               existing_nullable=False)
    op.alter_column('rag_user_feedback', 'bot_msg_id',
               existing_type=sa.BIGINT(),
               comment='ID сообщения бота',
               existing_nullable=False)
    op.alter_column('rag_user_feedback', 'retriever_type',
               existing_type=sa.VARCHAR(length=16),
               comment='Тип ретривера: новости, господдержка, гигачат',
               existing_nullable=False)
    op.alter_column('rag_user_feedback', 'reaction',
               existing_type=sa.BOOLEAN(),
               comment='Обратная связь от пользователя: True - положительная, False - отрицательная',
               existing_nullable=True)
    op.alter_column('rag_user_feedback', 'date',
               existing_type=postgresql.TIMESTAMP(),
               comment='Дата сообщения от бота',
               existing_nullable=True)
    op.alter_column('rag_user_feedback', 'query',
               existing_type=sa.TEXT(),
               comment='Запрос пользователя',
               existing_nullable=False)
    op.alter_column('rag_user_feedback', 'response',
               existing_type=sa.TEXT(),
               comment='Ответ на запрос пользователя',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rag_user_feedback', 'response',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Ответ на запрос пользователя',
               existing_nullable=True)
    op.alter_column('rag_user_feedback', 'query',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Запрос пользователя',
               existing_nullable=False)
    op.alter_column('rag_user_feedback', 'date',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Дата сообщения от бота',
               existing_nullable=True)
    op.alter_column('rag_user_feedback', 'reaction',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Обратная связь от пользователя: True - положительная, False - отрицательная',
               existing_nullable=True)
    op.alter_column('rag_user_feedback', 'retriever_type',
               existing_type=sa.VARCHAR(length=16),
               comment=None,
               existing_comment='Тип ретривера: новости, господдержка, гигачат',
               existing_nullable=False)
    op.alter_column('rag_user_feedback', 'bot_msg_id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='ID сообщения бота',
               existing_nullable=False)
    op.alter_column('rag_user_feedback', 'chat_id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='ID чата с пользователем',
               existing_nullable=False)
    op.drop_column('rag_user_feedback', 'rephrase_response')
    op.drop_column('rag_user_feedback', 'rephrase_query')
    op.drop_column('rag_user_feedback', 'history_response')
    op.drop_column('rag_user_feedback', 'history_query')
    # ### end Alembic commands ###
