"""Add RelationCommodityCommodityResearch for many-to-many relationship

Revision ID: 46e15b229b90
Revises: 8e72b159ccbf
Create Date: 2024-08-14 11:31:30.604706

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '46e15b229b90'
down_revision: Union[str, None] = '8e72b159ccbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    commodity_research_table = sa.table(
        'commodity_research',
        sa.column('id', sa.Integer),
        sa.column('commodity_id', sa.Integer)
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relation_commodity_commodity_research',
                    sa.Column('commodity_id', sa.Integer(), nullable=False),
                    sa.Column('commodity_research_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['commodity_id'], ['commodity.id'], onupdate='CASCADE', ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['commodity_research_id'], ['commodity_research.id'], onupdate='CASCADE',
                                            ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('commodity_id', 'commodity_research_id')
                    )
    op.execute(
        sa.insert(
            sa.table(
                'relation_commodity_commodity_research',
                sa.column('commodity_id', sa.Integer),
                sa.column('commodity_research_id', sa.Integer)
            )
        ).from_select(
            ['commodity_id', 'commodity_research_id'],
            sa.select(
                commodity_research_table.c.commodity_id,
                commodity_research_table.c.id
            ).where(commodity_research_table.c.commodity_id != None)
        )
    )
    op.drop_column('commodity_research', 'commodity_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commodity_research', sa.Column('commodity_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_table('relation_commodity_commodity_research')
    # ### end Alembic commands ###
