"""create_user_meeting

Revision ID: 1b2c4a5f8d9b
Revises: fb7cacc642f5
Create Date: 2024-04-11 14:52:00.688434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b2c4a5f8d9b'
down_revision: Union[str, None] = 'fb7cacc642f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_meeting',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('theme', sa.Text(), nullable=False, comment='Тема встречи'),
    sa.Column('date_start', sa.DateTime(), nullable=False, comment='Время начала встречи (UTC)'),
    sa.Column('date_end', sa.DateTime(), nullable=False, comment='Время окончания встречи (UTC)'),
    sa.Column('timezone', sa.Integer(), nullable=False, comment='Таймзона пользователя во время использования web app'),
    sa.Column('is_notify_first', sa.Boolean(), server_default=sa.text('false'), nullable=True, comment='Указывает на отправку первого уведомления'),
    sa.Column('is_notify_second', sa.Boolean(), server_default=sa.text('false'), nullable=True, comment='Указывает на отправку второго уведомления'),
    sa.Column('is_notify_last', sa.Boolean(), server_default=sa.text('false'), nullable=True, comment='Указывает на отправку последнего уведомления'),
    sa.Column('description', sa.Text(), nullable=True, comment='Описание встречи'),
    sa.ForeignKeyConstraint(['user_id'], ['whitelist.user_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Перечень встреч пользователей'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_meeting')
    # ### end Alembic commands ###
