"""call_reports

Revision ID: f4b27e7052d3
Revises: 1b2c4a5f8d9b
Create Date: 2024-04-12 20:46:06.584106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4b27e7052d3'
down_revision: Union[str, None] = '1b2c4a5f8d9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_call_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='Айди пользователя'),
    sa.Column('client', sa.String(length=255), nullable=False, comment='Клиент'),
    sa.Column('report_date', sa.Date(), nullable=False, comment='Дата проведения встречи'),
    sa.Column('description', sa.Text(), nullable=False, comment='Отчет по встрече'),
    sa.ForeignKeyConstraint(['user_id'], ['whitelist.user_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'user_id'),
    comment='Записи call reports'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bot_call_reports')
    # ### end Alembic commands ###
