"""del reports tables

Revision ID: d1e69058e32f
Revises: 9982181d8fe8
Create Date: 2024-11-22 15:06:24.750427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'd1e69058e32f'
down_revision: Union[str, None] = '9982181d8fe8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report_eco_mon')
    op.drop_table('report_exc_day')
    op.drop_table('report_met_day')
    op.drop_table('report_eco_day')
    op.drop_table('report_bon_mon')
    op.drop_table('report_exc_mon')
    op.drop_table('report_bon_day')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_bon_day',
    sa.Column('0', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('1', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('2', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_table('report_exc_mon',
    sa.Column('0', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('1', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('2', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_table('report_bon_mon',
    sa.Column('0', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('1', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('2', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_table('report_eco_day',
    sa.Column('0', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('1', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('2', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_table('report_met_day',
    sa.Column('0', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('1', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('2', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_table('report_exc_day',
    sa.Column('0', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('1', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('2', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_table('report_eco_mon',
    sa.Column('0', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('1', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('2', sa.TEXT(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
