"""fix_is_new_in_products

Revision ID: 5f549e4ab5c8
Revises: 93a8990e8897
Create Date: 2024-12-26 10:43:13.013947

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5f549e4ab5c8'
down_revision: Union[str, None] = '93a8990e8897'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bot_product', 'is_new')
    op.add_column(
        'bot_product_document',
        sa.Column(
            'is_new',
            sa.Boolean(),
            nullable=True,
            comment='Новый ли файл, отвечает за отправку пользователям'
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bot_product_document', 'is_new')
    op.add_column(
        'bot_product',
        sa.Column(
            'is_new',
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=True,
            comment='Новый ли продукт, отвечает за отправку продуктов пользователям'
        )
    )
    # ### end Alembic commands ###
