"""add_new_broadcast_version

Revision ID: 9eef2eb76ee8
Revises: 7c3b2d9e1234
Create Date: 2025-01-12 18:29:10.883776

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9eef2eb76ee8'
down_revision: Union[str, None] = '7c3b2d9e1234'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'broadcast_version',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('broadcast_id', sa.BigInteger(), nullable=False),
        sa.Column('message_text', sa.Text(), nullable=True),
        sa.Column('message_type_id', sa.Integer(), nullable=False),
        sa.Column('function_name', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('author_id', sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(['author_id'], ['registered_user.user_id'], onupdate='CASCADE', ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['broadcast_id'], ['broadcast.id'], onupdate='CASCADE', ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['message_type_id'], ['message_type.id'], onupdate='CASCADE', ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        comment='Версии рассылок сообщений в боте'
    )
    op.create_table(
        'relation_telegram_file_broadcast_version',
        sa.Column('telegram_file_id', sa.BigInteger(), nullable=True),
        sa.Column('broadcast_version_id', sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(['broadcast_version_id'], ['broadcast_version.id'], onupdate='CASCADE',
                                ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['telegram_file_id'], ['telegram_file.id'], onupdate='CASCADE', ondelete='CASCADE')
    )

    op.add_column('broadcast', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint('broadcast_message_type_id_fkey', 'broadcast', type_='foreignkey')
    op.drop_column('broadcast', 'message_type_id')
    op.drop_column('broadcast', 'function_name')
    op.drop_column('broadcast', 'text')
    op.drop_constraint('telegram_file_broadcast_id_fkey', 'telegram_file', type_='foreignkey')
    op.drop_column('telegram_file', 'broadcast_id')
    op.add_column('telegram_message', sa.Column('broadcast_version_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'telegram_message', 'broadcast_version', ['broadcast_version_id'], ['id'], onupdate='CASCADE',
                          ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telegram_message', 'broadcast_version_id')
    op.add_column('telegram_file', sa.Column('broadcast_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.create_foreign_key('telegram_file_broadcast_id_fkey', 'telegram_file', 'broadcast', ['broadcast_id'], ['id'],
                          onupdate='CASCADE', ondelete='CASCADE')
    op.add_column('broadcast', sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('broadcast', sa.Column('function_name', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('broadcast', sa.Column('message_type_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.create_foreign_key('broadcast_message_type_id_fkey', 'broadcast', 'message_type', ['message_type_id'], ['id'],
                          onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('broadcast', 'deleted_at')
    op.drop_table('relation_telegram_file_broadcast_version')
    op.drop_table('broadcast_version')
    # ### end Alembic commands ###
