"""create rag_user_feedback

Revision ID: 2e8cea167b16
Revises: 8f98a67434f7
Create Date: 2024-03-19 16:20:11.527379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e8cea167b16'
down_revision: Union[str, None] = '8f98a67434f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rag_user_feedback',
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('bot_msg_id', sa.BigInteger(), nullable=False),
    sa.Column('retriever_type', sa.String(length=16), nullable=False),
    sa.Column('reaction', sa.Boolean(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('response', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('chat_id', 'bot_msg_id'),
    comment='Обратная связь от пользователей по работе с RAG-системой'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rag_user_feedback')
    # ### end Alembic commands ###
