"""Concat research_source and quote_source tables

Revision ID: 8f98a67434f7
Revises: 9caf77c81d11
Create Date: 2024-03-13 15:42:27.750020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from migrations.data import sources

# revision identifiers, used by Alembic.
revision: str = '8f98a67434f7'
down_revision: Union[str, None] = '865943b6e583'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def add_source_groups(source_grp_table) -> None:
    op.bulk_insert(source_grp_table, sources.groups)


def add_sources(source_table) -> None:
    op.bulk_insert(source_table, sources.sources)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    source_group_table = op.create_table('source_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('name_latin', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='Справочник выделенных подгрупп среди источников'
    )
    parser_source_table = op.create_table('parser_source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('alt_names', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('response_format', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('source_group_id', sa.Integer(), nullable=False),
    sa.Column('last_update_datetime', sa.DateTime(), nullable=True),
    sa.Column('previous_update_datetime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_group_id'], ['source_group.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Справочник источников'
    )
    op.drop_table('quote_source')
    op.drop_table('quote_group')
    op.drop_table('research_source')
    # ### end Alembic commands ###
    add_source_groups(source_group_table)
    add_sources(parser_source_table)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('research_source',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('response_format', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('source', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('last_update_datetime', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('previous_update_datetime', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='research_source_pkey')
    )
    op.create_table('quote_group',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='quote_group_pkey'),
    comment='Справочник выделенных среди котировок подгрупп'
    )
    op.create_table('quote_source',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('alias', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('block', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('response_format', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('source', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('last_update_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('quote_group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('previous_update_datetime', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['quote_group_id'], ['quote_group.id'], name='quote_group_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='quote_source_pkey'),
    comment='Справочник источников котировок'
    )
    op.drop_table('parser_source')
    op.drop_table('source_group')
    # ### end Alembic commands ###
