name: CI_main

on:
  push:
    branches: [Develop]
    paths-ignore:
      - "data/**"
      - "sources/**"
  pull_request:
    branches: [Develop]
    paths-ignore:
      - "data/**"
      - "sources/**"

jobs:
  testing:
    runs-on: self-hosted
    services:
      postgres:
        image: postgres:15
        ports:
          - 5005:5005
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
        options: >-
          --health-cmd="pg_isready -U test_user" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=5

    strategy:
      fail-fast: false
      matrix:
        service:
          - service_path: 'src/projects/article'
            with_flake: true
            with_pylint: false
            with_tests: false

          - service_path: 'src/projects/article_online'
            with_flake: true
            with_pylint: false
            with_tests: false

          - service_path: 'src/projects/bot'
            with_flake: true
            with_pylint: false
            with_tests: false

          - service_path: 'src/projects/parser_monitoring'
            with_flake: true
            with_pylint: false
            with_tests: false

          - service_path: 'src/projects/quotes'
            with_flake: true
            with_pylint: false
            with_tests: false

          - service_path: 'src/projects/research'
            with_flake: true
            with_pylint: false
            with_tests: false

          - service_path: 'src/projects/users_statistics'
            with_flake: true
            with_pylint: false
            with_tests: false

          - service_path: 'src/projects/web_app'
            with_flake: false
            with_pylint: false
            with_tests: false

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Run flake8
        if: matrix.service.with_flake
        run: |
          poetry run python -m flake8 ${{ matrix.service.service_path }}

      - name: Run pylint
        if: matrix.service.with_pylint
        run: |
          poetry run python -m pylint ${{ matrix.service.service_path }}

      - name: Run pytest
        if: matrix.service.with_tests
        env:
          PSQL_ENGINE: postgresql://test_user:test_password@localhost:5005/test_db
          BOT_API_TOKEN: 7157864383:AAEfeSr7cGaY61I1NsaWMKLi322WwiaHbY5
        run: |
          poetry run python -m pytest ${{ matrix.service.service_path }}