# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: test_branch

on:
  push:
    branches: [Develop]
    paths-ignore:
      - "data/**"
      - "sources/**"
  pull_request:
    branches: [Develop]
    paths-ignore:
      - "data/**"
      - "sources/**"

jobs:
  build:
    strategy:
      matrix:
        dir: ['src/article', 'src/article_online', 'src/bot', 'src/parser_monitoring', 'src/quotes', 'src/research', 'src/user_statistics']
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"
      - name: Test
        run: |
          ls -la 
          pwd
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Run flake8
        run: |
          poetry run python -m pylint ${{ matrix.dir }}
      - name: Run pylint
        run: |
          poetry run python -m pylint ${{ matrix.dir }}
