name: CI_main

on:
  push:
    branches: [Develop]
    paths-ignore:
      - "data/**"
      - "sources/**"
  pull_request:
    branches: [Develop]
    paths-ignore:
      - "data/**"
      - "sources/**"

jobs:
  testing:
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        service:
          - matrix.service_path: 'src/article'
            matrix.with_flake: true
            matrix.with_pylint: true
            matrix.with_tests: true

          - matrix.service_path: 'src/article_online'
            matrix.with_flake: 'true'
            matrix.with_pylint: true
            matrix.with_tests: true

          - matrix.service_path: 'src/bot'
            matrix.with_flake: true
            matrix.with_pylint: true
            matrix.with_tests: true

          - matrix.service_path: 'src/parser_monitoring'
            matrix.with_flake: 'true'
            matrix.with_pylint: true
            matrix.with_tests: true

          - matrix.service_path: 'src/quotes'
            matrix.with_flake: true
            matrix.with_pylint: true
            matrix.with_tests: true

          - matrix.service_path: 'src/research'
            matrix.with_flake: 'true'
            matrix.with_pylint: true
            matrix.with_tests: true

          - matrix.service_path: 'src/users_statistics'
            matrix.with_flake: 'true'
            matrix.with_pylint: true
            matrix.with_tests: true

          - matrix.service_path: 'src/web_app'
            matrix.with_flake: true
            matrix.with_pylint: 'true'
            matrix.with_tests: true

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
#
#      - name: Install dependencies
#        run: |
#          python -m pip install --upgrade pip
#          pip install poetry
#          poetry install

      - name: Run flake8
        run: |
          echo ${{ matrix.with_flake }}
          if [ '123' -eq '123' ]; then echo "1233"; fi
          poetry run python -m flake8 ${{ matrix.service_path }}

#      - name: Run pylint
#        if: matrix.with_pylint
#        run: |
#          poetry run python -m pylint ${{ matrix.service_path }}
#
#      - name: Run pytest
#        if: ${{ matrix.with_tests == 'true' }}
#        run: |
#          poetry run python -m pytest ${{ matrix.service_path }}