name: CI_main

on:
  push:
    branches: [add_api_for_analytics]
    paths-ignore:
      - "data/**"
      - "sources/**"

jobs:
  run_test_tasks:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run flake, pylint and pytest
        uses: ./.github/workflows/ci_testing
        with:
          service_path: 'src/article'