name: CI_main

on:
  push:
    branches: [add_api_for_analytics]
    paths-ignore:
      - "data/**"
      - "sources/**"
  pull_request:
    branches: [add_api_for_analytics]
    paths-ignore:
      - "data/**"
      - "sources/**"

jobs:
  run_test_tasks:
    runs-on: self-hosted

    strategy:
      fail-fast: false
      matrix:
        service:
          - service_path: 'src/article'
            with_flake: true
          - service_path: 'src/article_online'
            with_flake: true
          - service_path: 'src/bot'
            with_flake: true
          - service_path: 'src/parser_monitoring'
            with_flake: true
          - service_path: 'src/quotes'
            with_flake: true
          - service_path: 'src/research'
            with_flake: true
          - service_path: 'src/users_statistics'
            with_flake: true
          - service_path: 'src/web_app'
            with_flake: true

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run flake, pylint and pytest
        uses: ./.github/workflows/ci_testing
        with:
          service_path: src/article
          with_flake: true
#          with_pylint: ${{ matrix.service.with_pylint }}
#          with_tests: ${{ matrix.service.with_tests }}