name: CI_main

on:
  push:
    branches: [Develop]
    paths-ignore:
      - "data/**"
      - "sources/**"
  pull_request:
    branches: [Develop]
    paths-ignore:
      - "data/**"
      - "sources/**"

jobs:
  testing:
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        service:
          - service_path: 'src/article'
            with_flake: true
            with_pylint: false
            with_tests: false

          - service_path: 'src/article_online'
            with_flake: true
            with_pylint: false
            with_tests: false

          - service_path: 'src/bot'
            with_flake: true
            with_pylint: false
            with_tests: false

          - service_path: 'src/parser_monitoring'
            with_flake: true
            with_pylint: false
            with_tests: false

          - service_path: 'src/quotes'
            with_flake: true
            with_pylint: false
            with_tests: false

          - service_path: 'src/research'
            with_flake: true
            with_pylint: false
            with_tests: false

          - service_path: 'src/users_statistics'
            with_flake: true
            with_pylint: false
            with_tests: false

          - service_path: 'src/web_app'
            with_flake: false
            with_pylint: false
            with_tests: true

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Run flake8
        if: matrix.service.with_flake
        run: |
          poetry run python -m flake8 ${{ matrix.service.service_path }}

      - name: Run pylint
        if: matrix.service.with_pylint
        run: |
          poetry run python -m pylint ${{ matrix.service.service_path }}

      - name: Run pytest
        if: matrix.service.with_tests
        run: |
          poetry run python -m pytest ${{ matrix.service.service_path }}