name: CI_main

on:
  push:
    branches: [ add_api_for_analytics ]
    paths-ignore:
      - "data/**"
      - "sources/**"
  pull_request:
    branches: [ add_api_for_analytics ]
    paths-ignore:
      - "data/**"
      - "sources/**"

jobs:
  run_test_tasks:
    strategy:
      fail-fast: false
      matrix:
        service:
          - path: 'src/article'
            with_flake: true
          - path: 'src/article_online'
            with_flake: true
          - path: 'src/bot'
            with_flake: true
          - path: 'src/parser_monitoring'
            with_flake: true
          - path: 'src/quotes'
            with_flake: true
          - path: 'src/research'
            with_flake: true
          - path: 'src/users_statistics'
            with_flake: true
          - path: 'src/web_app'
            with_flake: true
            with_tests: true

    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: TEST
        run: |
          echo ${{ matrix.service.path }}

      - name: Run flake, pylint and pytest
        uses: ./.github/workflows/ci_testing
        with:
          service_path: ${{ matrix.service.path }}
          with_flake: ${{ matrix.service.with_flake }}
#          with_pylint: ${{ matrix.service.with_pylint }}
#          with_tests: ${{ matrix.service.with_tests }}

